# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ysMiQZ3OE5-TIT5qCr4WikJXaI4Ib69H
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

df=pd.read_csv("/content/DSAI-LVA-DATASET for Quiz.csv")
df.info()

df.isnull().sum()

df

df.drop('ParentEducation',axis=1,inplace=True)

import random
k=['phd','masters','bachelors','school','no education']
for i in df.index:
  df.loc[i,'ParentEducation']=random.choice(k)
df

for i in df.index:
  if df.loc[i,'Pass']=='Yes':
    if df.loc[i,'PreviousTestScore']>85 and df.loc[i,'StudyTime']>=5:
      df.loc[i,'status']='Pass with highscore'
    else:
      df.loc[i,'status']='Pass with lowscore'
  else:
    df.loc[i,'status']='fail'

df=df.drop('Pass',axis=1)
df

df

x=df[['StudyTime','PreviousTestScore','ParentEducation']]
y=df['status']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
c1 = open('trainfile.csv', 'w')
arr1 = str(x_train)
arr2=str(y_train)
c1.write(arr1)
c1.write(arr2)
c1.close

c2 = open('testfile.csv', 'w')
arr3 = str(x_test)
arr4=str(y_test)
c2.write(arr3)
c2.write(arr4)
c2.close

df

from xgboost import XGBClassifier
Model=[RandomForestClassifier(n_estimators=100),DecisionTreeClassifier(),XGBClassifier(n_estimators=2)]
pred=[]
from sklearn.preprocessing import LabelEncoder
labe=LabelEncoder()
x_train['ParentEducation']=labe.fit_transform(x_train['ParentEducation'])
y_train['status']=labe.fit_transform(y_train['status'])
for i in Model:
  #a=pd.read_csv('/content/trainfile.csv')
  i.fit(x_train,y_train)
  k=i.predict(x_test)
  pred.append(k)